---

- name: Install collectd
  apt: name={{ item }} state=present
  with_items:
    - collectd-core

- name: Link Ubuntu config to proper one
  file: src=/etc/collectd.conf dest=/etc/collectd/collectd.conf state=link force=yes
