# Neutron
- tempest.api.network.admin.test_external_network_extension.ExternalNetworksTestJSON.test_delete_external_networks_with_floating_ip:
    In the Icehouse release Neutron does not support deleting an external network when ports are still in use on the network
- tempest.api.network.admin.test_l3_agent_scheduler.L3AgentSchedulerTestJSON.test_add_list_remove_router_on_l3_agent[gate,smoke]:
    The test creates a router and then tries to schedule it to L3-agent. The test will not pass in MOS because:
        1) In MOS handle_internal_only_routers = false and l3_agentschedulers_db.get_l3_agent_candidates blocks such routers;
        2) If the router is created with a gateway then it is scheduled automatically and the test fails with RouterHostedByL3Agent error

# Nova
- setUpClass (tempest.api.compute.floating_ips.test_floating_ips_actions.FloatingIPsTestJSON):
    Fails due to https://bugs.launchpad.net/mos/+bug/1370448
- setUpClass (tempest.api.compute.floating_ips.test_list_floating_ips.FloatingIPDetailsTestJSON):
    Fails due to https://bugs.launchpad.net/mos/+bug/1370448
- setUpClass (tempest.api.compute.servers.test_server_rescue.ServerRescueTestJSON)

# Keystone
- tempest.api.identity.admin.v3.test_policies.PoliciesTestJSON.test_create_update_delete_policy[gate,smoke]:
    The action you have requested has not been implemented
- tempest.api.identity.admin.v3.test_policies.PoliciesTestJSON.test_list_policies[gate,smoke]:
    The action you have requested has not been implemented
- tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON.test_grant_list_revoke_role_to_group_on_project[gate,smoke]
- tempest.api.identity.admin.v3.test_tokens.TokensV3TestJSON.test_tokens[gate,smoke]
- tempest.api.identity.admin.v3.test_tokens.TokensV3TestJSON.test_rescope_token[gate]
- tempest.api.identity.admin.v3.test_trusts.TrustsV3TestJSON.test_trust_expire[gate,smoke]
- tempest.api.identity.admin.v3.test_users.UsersV3TestJSON.test_update_user_password[gate]

# Orchestration
- setUpClass (tempest.api.orchestration.stacks.test_templates.TemplateAWSTestJSON)
- setUpClass (tempest.api.orchestration.stacks.test_templates.TemplateYAMLTestJSON)

# Sahara
- tempest.api.data_processing.test_data_sources.DataSourceTest.test_local_hdfs_data_source_create[gate,smoke]:
    Sahara does not support local HDFS data sources in the Icehouse release
- tempest.api.data_processing.test_data_sources.DataSourceTest.test_local_hdfs_data_source_delete[gate,smoke]:
    Sahara does not support local HDFS data sources in the Icehouse release
- tempest.api.data_processing.test_data_sources.DataSourceTest.test_local_hdfs_data_source_get[gate,smoke]:
    Sahara does not support local HDFS data sources in the Icehouse release
- tempest.api.data_processing.test_data_sources.DataSourceTest.test_local_hdfs_data_source_list[gate,smoke]:
    Sahara does not support local HDFS data sources in the Icehouse release

# Swift
- tempest.api.object_storage.test_account_bulk.BulkTest.test_bulk_delete[gate]
- tempest.api.object_storage.test_account_bulk.BulkTest.test_extract_archive[gate]
- tempest.api.object_storage.test_account_bulk.BulkTest.test_bulk_delete_by_POST[gate]
- tempest.api.object_storage.test_account_quotas_negative.AccountQuotasNegativeTest.test_user_modify_quota[gate,negative,smoke]
- tempest.api.object_storage.test_container_quotas.ContainerQuotasTest.test_upload_large_object[gate,smoke]
- tempest.api.object_storage.test_container_quotas.ContainerQuotasTest.test_upload_too_many_objects[gate,smoke]
- tempest.api.object_storage.test_container_staticweb.StaticWebTest.test_web_index
- tempest.api.object_storage.test_container_staticweb.StaticWebTest.test_web_listing_css
- tempest.api.object_storage.test_container_staticweb.StaticWebTest.test_web_error
- tempest.api.object_storage.test_crossdomain.CrossdomainTest.test_get_crossdomain_policy
- tempest.api.object_storage.test_object_formpost.ObjectFormPostTest.test_post_object_using_form[gate]
- tempest.api.object_storage.test_object_formpost_negative.ObjectFormPostNegativeTest.test_post_object_using_form_invalid_signature[gate]
- tempest.api.object_storage.test_object_formpost_negative.ObjectFormPostNegativeTest.test_post_object_using_form_expired[gate,negative]
- tempest.api.object_storage.test_object_services.PublicObjectTest.test_access_public_container_object_without_using_creds[gate,smoke]
- tempest.api.object_storage.test_object_slo.ObjectSloTest.test_delete_large_object[gate]
- tempest.api.object_storage.test_object_slo.ObjectSloTest.test_list_large_object_metadata[gate]
- tempest.api.object_storage.test_object_slo.ObjectSloTest.test_retrieve_large_object[gate]
- tempest.api.object_storage.test_object_slo.ObjectSloTest.test_upload_manifest[gate]
- tempest.api.object_storage.test_object_temp_url.ObjectTempUrlTest.test_get_object_using_temp_url_with_inline_query_parameter[gate]
- tempest.api.object_storage.test_object_temp_url_negative.ObjectTempUrlNegativeTest.test_get_object_after_expiration_time[gate,negative]
- tempest.api.object_storage.test_object_version.ContainerTest.test_versioned_container[gate,smoke]

# Scenario Tests
- tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup[compute,image,volume]
- tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_luks[compute,image,volume]
- tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario[compute,image,network,volume]
- tempest.scenario.test_shelve_instance.TestShelveInstance.test_shelve_instance[compute,image,network]
- tempest.scenario.test_snapshot_pattern.TestSnapshotPattern.test_snapshot_pattern[compute,image,network]
- tempest.scenario.test_swift_basic_ops.TestSwiftBasicOps.test_swift_acl_anonymous_download[object_storage]
- tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern[compute,image,volume]
- tempest.scenario.test_volume_boot_pattern.TestVolumeBootPatternV2.test_volume_boot_pattern[compute,image,volume]

# BOTO
- tempest.thirdparty.boto.test_ec2_network.EC2NetworkTest.test_disassociate_not_associated_floating_ip
- tempest.thirdparty.boto.test_s3_buckets.S3BucketsTest.test_create_and_get_delete_bucket
- tempest.thirdparty.boto.test_s3_objects.S3BucketsTest.test_create_get_delete_object
- tearDownClass (tempest.thirdparty.boto.test_s3_buckets.S3BucketsTest)

# CLI
- tempest.cli.simple_read_only.object_storage.test_swift.SimpleReadOnlySwiftClientTest.test_swift_capabilities
