---

- name: Set processes
  template: src=plugin_processes.j2 dest={{ collectd.dirs.conf }}/processes

- name: Set network
  template: src=plugin_network.j2 dest={{ collectd.dirs.conf }}/network

- name: Set CSV writer
  template: src=plugin_csv.j2 dest={{ collectd.dirs.conf }}/csv

- name: Set RRDTool writer
  template: src=plugin_rrdtool.j2 dest={{ collectd.dirs.conf }}/rrdtool

- name: Tune iptables
  command: iptables "{{ item }}" INPUT -p udp --dport "{{ collectd.network.port }}" -j ACCEPT
  ignore_errors: true
  with_items:
    - "-D"
    - "-I"

- name: Restart collectd
  service: name=collectd state=restarted
